var css_color_names = [
    "Black",
    "Navy",
    "DarkBlue",
    "MediumBlue",
    "Blue",
    "DarkGreen",
    "Green",
    "Teal",
    "DarkCyan",
    "DeepSkyBlue",
    "DarkTurquoise",
    "MediumSpringGreen",
    "Lime",
    "SpringGreen",
    "Aqua",
    "Cyan",
    "MidnightBlue",
    "DodgerBlue",
    "LightSeaGreen",
    "ForestGreen",
    "SeaGreen",
    "DarkSlateGray",
    "LimeGreen",
    "MediumSeaGreen",
    "Turquoise",
    "RoyalBlue",
    "SteelBlue",
    "DarkSlateBlue",
    "MediumTurquoise",
    "Indigo",
    "DarkOliveGreen",
    "CadetBlue",
    "CornflowerBlue",
    "MediumAquaMarine",
    "DimGray",
    "SlateBlue",
    "OliveDrab",
    "SlateGray",
    "LightSlateGray",
    "MediumSlateBlue",
    "LawnGreen",
    "Chartreuse",
    "Aquamarine",
    "Maroon",
    "Purple",
    "Olive",
    "Gray",
    "SkyBlue",
    "LightSkyBlue",
    "BlueViolet",
    "DarkRed",
    "DarkMagenta",
    "SaddleBrown",
    "DarkSeaGreen",
    "LightGreen",
    "MediumPurple",
    "DarkViolet",
    "PaleGreen",
    "DarkOrchid",
    "YellowGreen",
    "Sienna",
    "Brown",
    "DarkGray",
    "LightBlue",
    "GreenYellow",
    "PaleTurquoise",
    "LightSteelBlue",
    "PowderBlue",
    "FireBrick",
    "DarkGoldenRod",
    "MediumOrchid",
    "RosyBrown",
    "DarkKhaki",
    "Silver",
    "MediumVioletRed",
    "IndianRed",
    "Peru",
    "Chocolate",
    "Tan",
    "LightGray",
    "Thistle",
    "Orchid",
    "GoldenRod",
    "PaleVioletRed",
    "Crimson",
    "Gainsboro",
    "Plum",
    "BurlyWood",
    "LightCyan",
    "Lavender",
    "DarkSalmon",
    "Violet",
    "PaleGoldenRod",
    "LightCoral",
    "Khaki",
    "AliceBlue",
    "HoneyDew",
    "Azure",
    "SandyBrown",
    "Wheat",
    "Beige",
    "WhiteSmoke",
    "MintCream",
    "GhostWhite",
    "Salmon",
    "AntiqueWhite",
    "Linen",
    "LightGoldenRodYellow",
    "OldLace",
    "Red",
    "Fuchsia",
    "Magenta",
    "DeepPink",
    "OrangeRed",
    "Tomato",
    "HotPink",
    "Coral",
    "DarkOrange",
    "LightSalmon",
    "Orange",
    "LightPink",
    "Pink",
    "Gold",
    "PeachPuff",
    "NavajoWhite",
    "Moccasin",
    "Bisque",
    "MistyRose",
    "BlanchedAlmond",
    "PapayaWhip",
    "LavenderBlush",
    "SeaShell",
    "Cornsilk",
    "LemonChiffon",
    "FloralWhite",
    "Snow",
    "Yellow",
    "LightYellow",
    "Ivory",
    "White"
];


var card_colors = {
    "": "",
    "DimGray": "DimGray",
    "Black": "Black",
    "DarkGoldenrod": "DarkGoldenrod",
    "SaddleBrown": "SaddleBrown",
    "IndianRed": "IndianRed",
    "Maroon": "Maroon",
    "Indigo": "Indigo",
    "DarkBlue": "DarkBlue",
    "RoyalBlue": "RoyalBlue",
    "DarkGreen": "DarkGreen",
    "#666633": "#666633",
    "Navy": "Navy",          
    "MediumBlue": "MediumBlue",           
    "Blue": "Blue",           
    "Green": "Green",                
    "Teal": "Teal",                 
    "DarkCyan": "DarkCyan",             
    "DeepSkyBlue": "DeepSkyBlue",          
    "DarkTurquoise": "DarkTurquoise",        
    "MediumSpringGreen": "MediumSpringGreen",    
    "Lime": "Lime",                 
    "SpringGreen": "SpringGreen",          
    "Aqua": "Aqua",                 
    "Cyan": "Cyan",                 
    "MidnightBlue": "MidnightBlue",     
    "DodgerBlue": "DodgerBlue",
    "LightSeaGreen": "LightSeaGreen",
    "ForestGreen": "ForestGreen",
    "SeaGreen": "SeaGreen",
    "DarkSlateGray": "DarkSlateGray",
    "LimeGreen": "LimeGreen",
    "MediumSeaGreen": "MediumSeaGreen",
    "Turquoise": "Turquoise",
    "SteelBlue": "SteelBlue",
    "DarkSlateBlue": "DarkSlateBlue",
    "MediumTurquoise": "MediumTurquoise",
    "DarkOliveGreen": "DarkOliveGreen",
    "CadetBlue": "CadetBlue",
    "CornflowerBlue": "CornflowerBlue",
    "MediumAquaMarine": "MediumAquaMarine",
    "SlateBlue": "SlateBlue",
    "OliveDrab": "OliveDrab",
    "SlateGray": "SlateGray",
    "LightSlateGray": "LightSlateGray",
    "MediumSlateBlue": "MediumSlateBlue",
    "LawnGreen": "LawnGreen",
    "Chartreuse": "Chartreuse",
    "Aquamarine": "Aquamarine",
    "Maroon": "Maroon",
    "Purple": "Purple",
    "Olive": "Olive",
    "Gray": "Gray",
    "SkyBlue": "SkyBlue",
    "LightSkyBlue": "LightSkyBlue",
    "BlueViolet": "BlueViolet",
    "DarkRed": "DarkRed",
    "DarkMagenta": "DarkMagenta",
    "DarkSeaGreen": "DarkSeaGreen",
    "LightGreen": "LightGreen",
    "MediumPurple": "MediumPurple",
    "DarkViolet": "DarkViolet",
    "PaleGreen": "PaleGreen",
    "DarkOrchid": "DarkOrchid",
    "YellowGreen": "YellowGreen",
    "Sienna": "Sienna",
    "Brown": "Brown",
    "DarkGray": "DarkGray",
    "LightBlue": "LightBlue",
    "GreenYellow": "GreenYellow",
    "PaleTurquoise": "PaleTurquoise",
    "LightSteelBlue": "LightSteelBlue",
    "PowderBlue": "PowderBlue",
    "FireBrick": "FireBrick",
    "MediumOrchid": "MediumOrchid",
    "RosyBrown": "RosyBrown",
    "DarkKhaki": "DarkKhaki",
    "Silver": "Silver",
    "MediumVioletRed": "MediumVioletRed",
    "Peru": "Peru",
    "Chocolate": "Chocolate",
    "Tan": "Tan",
    "LightGray": "LightGray",
    "Thistle": "Thistle",
    "Orchid": "Orchid",
    "GoldenRod": "GoldenRod",
    "PaleVioletRed": "PaleVioletRed",
    "Crimson": "Crimson",
    "Gainsboro": "Gainsboro",
    "Plum": "Plum",
    "BurlyWood": "BurlyWood",
    "LightCyan": "LightCyan",
    "Lavender": "Lavender",
    "DarkSalmon": "DarkSalmon",
    "Violet": "Violet",
    "PaleGoldenRod": "PaleGoldenRod",
    "LightCoral": "LightCoral",
    "Khaki": "Khaki",
    "AliceBlue": "AliceBlue",
    "HoneyDew": "HoneyDew",
    "Azure": "Azure",
    "SandyBrown": "SandyBrown",
    "Wheat": "Wheat",
    "Beige": "Beige",
    "WhiteSmoke": "WhiteSmoke",
    "MintCream": "MintCream",
    "GhostWhite": "GhostWhite",
    "Salmon": "Salmon",
    "AntiqueWhite": "AntiqueWhite",
    "Linen": "Linen",
    "LightGoldenRodYellow": "LightGoldenRodYellow",
    "OldLace": "OldLace",
    "Red": "Red",
    "Fuchsia": "Fuchsia",
    "Magenta": "Magenta",
    "DeepPink": "DeepPink",
    "OrangeRed": "OrangeRed",
    "Tomato": "Tomato",
    "HotPink": "HotPink",
    "Coral": "Coral",
    "DarkOrange": "DarkOrange",
    "LightSalmon": "LightSalmon",
    "Orange": "Orange",
    "LightPink": "LightPink",
    "Pink": "Pink",
    "Gold": "Gold",
    "PeachPuff": "PeachPuff",
    "NavajoWhite": "NavajoWhite",
    "Moccasin": "Moccasin",
    "Bisque": "Bisque",
    "MistyRose": "MistyRose",
    "BlanchedAlmond": "BlanchedAlmond",
    "PapayaWhip": "PapayaWhip",
    "LavenderBlush": "LavenderBlush",
    "SeaShell": "SeaShell",
    "Cornsilk": "Cornsilk",
    "LemonChiffon": "LemonChiffon",
    "FloralWhite": "FloralWhite",
    "Snow": "Snow",
    "Yellow": "Yellow",
    "LightYellow": "LightYellow",
    "Ivory": "Ivory",
    "White": "White",
}
