version: '3'
services:
  rpgcards:
    container_name: rpgcards
    image: gelse/rpgcards:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 1888:80
